version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/CooreWireV1"
    schedule:
      interval: "weekly"
  - package-ecosystem: "pip"
    directory: "/CooreWireV1/apps/api"
    schedule:
      interval: "weekly"
