import test from "node:test";
import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { resolve } from "node:path";

test("renders owner admin shell with control and review sections", () => {
  const pageSource = readFileSync(resolve("app/admin/page.tsx"), "utf8");
  const shellSource = readFileSync(resolve("components/admin/admin-shell.tsx"), "utf8");
  const globalStyles = readFileSync(resolve("app/globals.css"), "utf8");

  assert.match(pageSource, /AdminShell/);
  assert.match(pageSource, /ArticleManager/);
  assert.match(pageSource, /ProgrammingControls/);
  assert.match(pageSource, /getAdminContent/);
  assert.match(pageSource, /getAdminDraft/);
  assert.match(pageSource, /searchParams/);
  assert.match(pageSource, /getProgrammingSettings/);
  assert.match(pageSource, /cw-app-shell/);
  assert.match(pageSource, /cw-surface/);
  assert.match(pageSource, /cw-admin-sidebar/);
  assert.match(pageSource, /cw-admin-main/);
  assert.match(pageSource, /cw-admin-utility/);
  assert.match(pageSource, /href="#drafts"/);
  assert.match(pageSource, /href="#programming"/);
  assert.match(shellSource, /Owner Workspace/i);
  assert.match(shellSource, /cw-admin-overview/);
  assert.match(shellSource, /cw-admin-stat-grid/);
  assert.match(shellSource, /admin-shell__signal/);
  assert.match(shellSource, /Review Queue/i);
  assert.match(shellSource, /System Health/i);
  assert.match(globalStyles, /\.cw-app-shell/);
  assert.match(globalStyles, /\.cw-surface/);
  assert.match(globalStyles, /\.cw-shell--light/);
  assert.match(globalStyles, /\.cw-admin-sidebar/);
  assert.match(globalStyles, /\.cw-admin-main/);
  assert.match(globalStyles, /\.cw-admin-utility/);
  assert.match(globalStyles, /\.admin-shell__panel-header/);
  assert.match(globalStyles, /\.admin-editor\s*\{/);
  assert.match(globalStyles, /\.cw-admin-workspace/);
  assert.match(globalStyles, /\.admin-editor__actions/);
});
