import test from "node:test";
import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { resolve } from "node:path";

test("renders homepage as a DW/ZDF-style active public news surface", () => {
  const pageSource = readFileSync(resolve("app/page.tsx"), "utf8");
  const heroSource = readFileSync(resolve("components/home/hero-story.tsx"), "utf8");
  const railSource = readFileSync(resolve("components/home/intelligence-rail.tsx"), "utf8");
  const gridSource = readFileSync(resolve("components/home/story-grid.tsx"), "utf8");
  const developingSource = readFileSync(resolve("components/home/developing-stories.tsx"), "utf8");
  const headerSource = readFileSync(resolve("components/public/public-header.tsx"), "utf8");
  const globalStyles = readFileSync(resolve("app/globals.css"), "utf8");

  assert.match(pageSource, /PublicHeader/);
  assert.match(pageSource, /cw-dw-lead-cluster/);
  assert.match(pageSource, /cw-latest-desk/);
  assert.match(pageSource, /cw-top-band/);
  assert.match(pageSource, /cw-analysis-zone/);
  assert.match(pageSource, /cw-current-feed/);
  assert.match(headerSource, /cw-zdf-topbar/);
  assert.match(headerSource, /cw-zdf-nav/);
  assert.match(headerSource, /CoreWire/);
  assert.match(headerSource, /Newsletter/);
  assert.match(heroSource, /cw-dw-lead-cluster/);
  assert.match(heroSource, /cw-lead-stack/);
  assert.match(heroSource, /cw-lead-visual/);
  assert.match(heroSource, /cw-lead-copy/);
  assert.match(heroSource, /href=\{`\/articles\/\$\{story\.slug\}`\}/);
  assert.match(heroSource, /Read full report/i);
  assert.match(gridSource, /cw-top-band/);
  assert.match(gridSource, /cw-top-band-card/);
  assert.match(gridSource, /href=\{`\/articles\/\$\{story\.slug\}`\}/);
  assert.match(railSource, /cw-latest-desk/);
  assert.match(railSource, /cw-latest-stack/);
  assert.match(railSource, /href=\{`\/articles\/\$\{entry\.slug\}`\}/);
  assert.match(developingSource, /cw-current-feed/);
  assert.match(developingSource, /cw-section-band/);
  assert.match(developingSource, /href=\{`\/articles\/\$\{story\.slug\}`\}/);
  assert.match(globalStyles, /\.cw-zdf-topbar/);
  assert.match(globalStyles, /\.cw-zdf-nav/);
  assert.match(globalStyles, /\.cw-dw-lead-cluster/);
  assert.match(globalStyles, /\.cw-latest-desk/);
  assert.match(globalStyles, /\.cw-top-band/);
  assert.match(globalStyles, /\.cw-current-feed/);
});
