import test from "node:test";
import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { resolve } from "node:path";

test("renders homepage as a clean-slate luxury lead-first surface", () => {
  const pageSource = readFileSync(resolve("app/page.tsx"), "utf8");
  const heroSource = readFileSync(resolve("components/home/hero-story.tsx"), "utf8");
  const railSource = readFileSync(resolve("components/home/intelligence-rail.tsx"), "utf8");
  const gridSource = readFileSync(resolve("components/home/story-grid.tsx"), "utf8");
  const developingSource = readFileSync(resolve("components/home/developing-stories.tsx"), "utf8");
  const headerSource = readFileSync(resolve("components/public/public-header.tsx"), "utf8");
  const globalStyles = readFileSync(resolve("app/globals.css"), "utf8");

  assert.match(pageSource, /PublicHeader/);
  assert.match(pageSource, /cw-lead-stage/);
  assert.match(pageSource, /cw-support-strip/);
  assert.match(pageSource, /cw-curated-feed/);
  assert.match(headerSource, /cw-signal-chip/);
  assert.match(headerSource, /cw-minimal-topbar/);
  assert.match(headerSource, /cw-primary-nav/);
  assert.match(headerSource, /CoreWire/);
  assert.match(headerSource, /Newsletter/);
  assert.match(heroSource, /cw-lead-stage/);
  assert.match(heroSource, /cw-lead-frame/);
  assert.match(heroSource, /cw-lead-media/);
  assert.match(heroSource, /cw-lead-content/);
  assert.match(heroSource, /cw-lead-actions/);
  assert.match(heroSource, /href=\{`\/articles\/\$\{story\.slug\}`\}/);
  assert.match(heroSource, /Read full report/i);
  assert.match(gridSource, /cw-support-strip/);
  assert.match(gridSource, /cw-support-card/);
  assert.match(gridSource, /href=\{`\/articles\/\$\{story\.slug\}`\}/);
  assert.match(railSource, /cw-curated-feed/);
  assert.match(railSource, /cw-feed-column/);
  assert.match(railSource, /href=\{`\/articles\/\$\{entry\.slug\}`\}/);
  assert.match(developingSource, /cw-brief-ribbon/);
  assert.match(developingSource, /href=\{`\/articles\/\$\{story\.slug\}`\}/);
  assert.match(globalStyles, /\.cw-lead-stage/);
  assert.match(globalStyles, /\.cw-support-strip/);
  assert.match(globalStyles, /\.cw-curated-feed/);
  assert.match(globalStyles, /\.cw-minimal-topbar/);
});
