apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: corewire
  namespace: corewire
spec:
  rules:
    - host: corewire.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: corewire-web
                port:
                  number: 3000
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: corewire-api
                port:
                  number: 8000
